neptune-mutual-blue/neptunemutual.com

src/views/about/Team.astro
src/views/about/Team.scss

Center the team slider

---

src/elements/icons/paths.ts
src/react-code/Encoder/History.jsx
src/react-code/Encoder/index.jsx

- Added a  delete feature on Previous Contract

ABI delete feature

---

.env.example
.vscode/settings.json
service/builder/fetch/index.ts
service/builder/syndication/feeds/item.ts
src/components/Header/VideoSection.astro
src/views/PolicyPage.astro
src/views/ProgramDetail.astro
src/views/VacancyDetail.astro
src/views/about/Roadmap.astro
src/views/blog-post/BlogPost.astro
types/api.d.ts
types/enum.ts
util/content-viewer/tasks/update-images.ts

- Updated fields based on CMS Editor Refactors
- Added new API: `hacks`

CMS Editor Refactors

---

.eslintrc.js

- Added `no-default-export` rule to disable default export.

Disable export default

---

astro.config.ts
service/builder/fetch/index.ts
service/builder/index.ts
src/data/structured/logo.ts
src/views/homepage/Hero.astro
types/custom.d.ts
types/enum.ts
types/svg.d.ts
types/svg.raw.d.ts

- Fixed eslint errors
- Added a workaround to avoid prettier's conflict with `application/ld+json` parser

Fix Lint Errors

---

astro.config.ts
package.json
src/components/ArticleCard.astro

Fixed build error for images without alt

Fix Build Error

---

src/scripts/protocol/dropdown.js
src/views/Ecosystem.scss
src/views/protocol/NetworkSelect.astro
src/views/protocol/NetworkSelect.scss

- Mobile view network dropdown in `/protocol/*` page style updated
- Dropdown list item focus outline fix
- Dropdown close when clicked outside
- Updated ecosystem carousel items to snap for better experience

Updated protocols page Network Dropdown 

---

src/components/Header/Section.scss
src/elements/Breadcrumb.scss
src/elements/Pagination.scss
src/pages/protocol/protocol.scss
src/views/about/team.ts
src/views/marketplace/MarketplaceOptions.astro
src/views/protocol/ContractDetails.astro
src/views/protocol/ContractDetails.scss

- Remove facebook from Edward's profile
- Fix the resources menu
- On Marketplace open the app in current tab instead of new tab
- Update breadcrumb on protocol contracts
- The active state color in blog pagination is incorrect.

Minor website fixes

---

src/pages/blog/index.astro
src/pages/blog/page/[page].astro

- Skip first three items in blog index to avoid redundancy from top three latest.

Skip first three items in blog

---

src/scripts/docs/index.js
src/scripts/docs/sidebar.js
src/views/Docs.astro
src/views/Docs.scss

- Added content sidebar for documentation TOC 
- Added script for documentation sidebar toggle
- Show sidebar when no javascript available
- Updated conflicting overlay implementation for content-sidebar & search
- Close search modal when clicked on the backdrop
https://neptunemutual-com-git-docs-sidebar-rupak-nm.vercel.app/docs

Docs sidebar

---

src/components/Seo.astro
src/pages/docs/index.astro

Fixed canonical URL of the documentation landing page

Fixed Canonical

---

src/pages/docs/index.astro
src/views/Docs-code.scss
src/views/Docs.scss

- Improved message styles.
- Fixed docs homepage SEO

Style Improvements

---

src/scripts/docs/index.js
src/styles/global.scss
src/views/Docs.scss

- Updated ui message alerts styles for dark mode
- Search modal position updated for mobile view
- Code section border issue fixed
- Disabled vertical page scrolling when docs search modal is visible

Docs fixes

---

src/views/homepage/Hero.astro

Updated home page hero section content

Updated content

---

util/pagination.ts

Current Behavior:
- Updated `getPagination` function by fixing the bug
- Used constants `EDGE_COUNT` & `MIDDLE_COUNT` for number of items in pagination start, middle & end
- Created functions `getMiddlePages`, `getPreviousPage` & `getNextPage` for better readability

Pagination bug fix

---

src/components/ArticleCard.scss

Changed Recent Blog Post Content Max-Lines

---

src/pages/hack-database/index.scss
src/scripts/hack-database/table/renderers.ts
src/views/hack-database/HackTable.astro
util/abbreviate-hack-database-amount.ts

- Abbreviated only dollar amounts for hack database
- Added tooltips

Abbreviated dollar amounts on hack database

---

astro.config.ts
util/html-processor/index.ts

Updated config and runtime error

---

src/components/EmailSubscription.scss
src/components/HeaderSection.astro
src/components/HeaderSection.scss
src/components/NftCard.astro
src/components/NftCard.scss
src/elements/Icon.scss
src/elements/icons/paths.ts
src/examples/HeaderExample.astro
src/pages/nft/marketplace.astro
src/pages/nft/marketplace.scss
src/react-code/lib/connect-wallet/Disclaimer.jsx
src/scripts/nft/marketplace.js
src/views/NftMarketplace.astro
src/views/Pressroom.astro
src/views/nft-marketplace/Hero.astro
src/views/nft-marketplace/Hero.scss

- Created marketplace hero, Nft Card component
- Updated docs links

Created Nft Card Component

---

src/layouts/BaseLayout.astro
src/scripts/global/theme/index.js

- Added theme to be obtained via query parameter
- Query parameter is replaced after page load
- The data from query param is saved into localStorage

Added support for theme via query selector

---

service/builder/syndication/sitemap/dynamic/config.ts
service/builder/syndication/sitemap/dynamic/index.ts
service/builder/syndication/sitemap/pages.json

- Added `Docs` Api to the dynamic builder
- Added protocol contracts
- Added marketplace
- Added hack-database

Added missing pages to sitemap

---

src/components/ContentViewer.scss
src/views/blog-post/BlogPostHero.astro
src/views/blog-post/BlogPostHero.scss

Blog Responsive

---

src/elements/content/Content.scss
src/views/Docs.scss

Fixed dark mode hover colors

---

.vscode/settings.json
package.json
src/elements/content/Content.scss
src/scripts/blog/slug.js
src/scripts/docs/index.js
yarn.lock

- Fixed incorrect implementation of table cell whitespace
- Refactored the styling of code blocks
- Added line numbers to code blocks

Fixed Style

---

src/data/footer.ts
src/scripts/about/index.js

- Fixed about us slider which seemed to be broken after the recent removal of team slider
- Updated Community Forums Link to open in new tab

Fixed About Page Slider and Updated Link on Footer

---

src/pages/policies/index.scss

- Added missing styles for button on Policies page

Added missing button styles on policies page

---

lib/hljs-solidity/common.js
lib/hljs-solidity/index.js
lib/hljs-solidity/languages/solidity.js
package.json
src/components/BlogAndPressroomViewer.scss
src/design-system/theme/_dark.scss
src/design-system/theme/_light.scss
src/elements/content/Content.scss
src/scripts/blog/slug.js
src/scripts/docs/index.js
src/scripts/utils/setup-hljs.js

- Added light mode for documentation codeblocks
- Improved syntax highlighting
- Added support for solidity code
- Added copy button

Improvement: Added light mode and improved syntax highlighting on documentation

---

src/components/DetailedListView.scss
src/views/VacancyDetail.scss
src/views/careers/vacancies/VacancyCard.scss
src/views/hack-database/HackTable.astro
src/views/hack-database/HackTable.scss

- Fixed career card background color
- Fixed **"About this Vacancy"** title background color in career detail
- Align chain icons in a hack database table
- Fixed background hover color of `DetailedListView`

fix: career card background and chain icons alignment in hacktable

---

src/elements/Input.scss
src/react-code/Encoder/Func.jsx
src/react-code/Encoder/FunctionType/encode.jsx
src/react-code/Encoder/FunctionType/read.jsx
src/react-code/Encoder/FunctionType/write.jsx
src/react-code/Encoder/Result.jsx
src/react-code/Encoder/components/InputFields.jsx
src/react-code/Encoder/helpers/solidity/methods.js
src/react-code/Encoder/helpers/web3-tools/abi-encoder.js
src/react-code/Encoder/hooks/useContractCall.jsx
src/react-code/components/icons/MetamaskDarkIcon.jsx

- updated function signature for encoding data
- updated argument structure data encode/read/write
- resturctured files for simplification

Abi Encoder update

---

service/api/index.ts
service/builder/fetch/index.ts
src/data/protocol.ts
src/pages/protocol/bsc/contracts.astro
src/pages/protocol/bsc/cx-tokens.astro
src/pages/protocol/bsc/pods.astro
src/react-code/Encoder/helpers/wallet/chains.js
src/views/homepage/launch-app/networks.ts
src/views/homepage/launch-app/popup.astro
src/views/marketplace/networks.ts
types/enum.ts

- Added BSC Network:
- protocol contracts pages
- homepage Launch App popup
- marketplace page
- Upated builder to fetch bsc protocol contracts

Added BSC Network

---

src/react-code/Encoder/FunctionType/read.jsx
src/react-code/Encoder/FunctionType/read.scss
src/react-code/Encoder/FunctionType/write.jsx
src/react-code/Encoder/helpers/solidity/methods.js
src/react-code/Encoder/helpers/wallet/chains.js
src/react-code/Encoder/helpers/web3-tools/abi-encoder.js
src/react-code/Encoder/hooks/useContractCall.jsx
src/react-code/components/ConnectWallet/ConnectedDropdown.jsx

- Fixed read method arguments
- Error parsing using interface
- Updated output ui for read methods
- Shown success message for read methods without output
- Updated chains list

Abi Encoder issues

---

src/pages/404.astro
src/scripts/404/index.js

added global script to 404 page to resolve the issue of theme selector & resource menu not working

Fix:404 page issues

---

src/scripts/global/search/find.js

- Removed the search result limit of 10 results

Removed search limitation of only 10 results

---

package.json
src/react-code/components/ConnectWallet/ConnectedDropdown.jsx
yarn.lock

- Removed `react-hotkeys-hook` dependency
- Removed shortcut

Removed disconnect wallet shortcut

---

service/api/index.ts
service/builder/fetch/index.ts
src/data/protocol.ts
src/elements/icons/paths.ts
src/layouts/BaseLayout.astro
src/pages/protocol/[network]/[type].astro
src/scripts/global/theme/index.js
types/enum.ts

- Fixed URL parsing for theme selection
- Updated incorrect `replaceState`
- Simplified `getTheme` function
- Replaced base-goerli with mumbai contracts

Fixed errors

---

src/components/RichTextContent.scss

- Fixed twitter embed styles in blog posts

Fixed styles for embedded tweets

---

service/builder/fetch/index.ts
src/scripts/contact/form/request.js

- Increased page size
- Show error message to the user in contact form

Fix errors

---

service/api/blog.ts
service/api/index.ts
service/builder/fetch/request.ts
service/builder/syndication/feeds/builder.ts
service/builder/syndication/feeds/item.ts

- Removed error handling during build.
- Handled `undefined` objects

Fix error handling and improve code structure

---

src/elements/buttons/Button.astro
src/react-code/components/Button/Button.jsx
src/react-code/components/Modal/Modal.jsx

- Fixed build errors caused by radix-ui dialog

Fixed build errors

---

src/react-code/components/InputWithLabel/InputModals.jsx
src/react-code/components/InputWithLabel/InputWithLabel.jsx
src/react-code/components/JSONPopup/JSONPopup.jsx
src/views/homepage/hero/PressroomAnnouncement.astro
src/views/homepage/hero/PressroomAnnouncement.scss
src/views/pressroom/Announcements.astro

- Added gradient animation to the pressroom announcement link

Added gradient animation to the announcement link
